version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cloop-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloop
    ports:
      - "3306:3306"
    volumes:
      - cloop-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloop-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - cloop-net

volumes:
  cloop-data:

networks:
  cloop-net: