spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG
