server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:uploads/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

google:
  client-ids:
    - "407408718192.apps.googleusercontent.com" #웹 애플리케이션용
#    - 프론트(안드로이드) 추가해야 함

logging:
  level:
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

gemini:
  api:
    key: ${GEMINI_API_KEY}

server:
  port: 8081