server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    # 사진 업로드 용량 제한
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      static-locations: file:uploads/

google:
  client-ids:
    - "407408718192.apps.googleusercontent.com" #웹 애플리케이션용
    - "282924798851-uh774utke2hogar5k15dro0c1klbg9la.apps.googleusercontent.com" # 안드로이드 client ID
    - "282924798851-2lhulrjvhnhs963tnjq88n4iq72a8lia.apps.googleusercontent.com" # 웹 client ID

logging:
  level:
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
    org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

gemini:
  api:
    key: ${GEMINI_API_KEY}

app:
  base-url: ${APP_BASE_URL}
