name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # 실패 시 즉시 종료
            cd CLOOP-Server

            # 최신 코드로 강제 리셋 (추적 파일만 영향)
            git fetch origin
            git reset --hard origin/main
            
            chmod +x gradlew
            ./gradlew build -x test

            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d
          EOF
