name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd CLOOP-Server

            # 작업 디렉토리 안의 변경사항을 모두 삭제
            git reset --hard
            git clean -fd  # 비추적 파일도 삭제됨

            git pull origin main

            ./gradlew build -x test

            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d
          EOF